spring:
  application:
    name: pizzeria
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:pizzeria;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXk=
  expiration: 3600000

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: INFO
    com.example.pizzeria: DEBUG
